# Uploading the files


In [ ]:
from google.colab import files
uploaded = files.upload()


Saving 8.csv to 8 (1).csv


In [ ]:
import numpy as np
import pandas as pd


# Extracting the land use data
lU/# of busstation/# of school,university,library/# of shops,malls/ # of banks/# of restaurants,bars/# of recrational centres,gyms/ # of convenience stores/# of Hospitals,clinics

In [ ]:
def features_lu():

  num_loc = 94  #number of intersections
  num_data = 0  #number of all of the data points
  #140
  interested_col1 = [132,133,134,135,136,137,138,139,140]#extracting the interested columns
  interested_col1 = list(np.asarray(interested_col1) - 1) #python numbering is starting from 0
  #124
  interested_col2 = [116,117,118,119,120,121,122,123,124]#extracting the interested columns
  interested_col2 = list(np.asarray(interested_col2) - 1) #python numbering is starting from 0
  #44
  interested_col3 = [36,37,38,39,40,41,42,43,44]#extracting the interested columns
  interested_col3 = list(np.asarray(interested_col3) - 1) #python numbering is starting from 0
  fe = np.empty(0)
  for i in range(1,num_loc+1):
      
      
      # Order of the columns are different in some intersections
    if i == 3 or i == 4 or i == 20 or i == 27 or i == 32 or i == 53 or i == 56 or i == 59 or i == 71 or i == 93 or i == 94 :
          f1 = str(i) + ".csv"
          intersection_fe = np.genfromtxt(f1, delimiter=',',skip_header=1,usecols=interested_col2,filling_values=0, )
          num_rows = intersection_fe.shape[0]
          intersection_fe_ = np.tile(intersection_fe[0],(num_rows,1))
          num_data = num_data + num_rows
          fe = np.append(fe,intersection_fe_)
    elif i == 58 or i == 2 :
          f2 = str(i) + ".csv"
          intersection_fe = np.genfromtxt(f2, delimiter=',',skip_header=1,usecols=interested_col3,filling_values=0, )
          num_rows = intersection_fe.shape[0]
          intersection_fe_ = np.tile(intersection_fe[0],(num_rows,1))
          num_data = num_data + num_rows
          fe = np.append(fe,intersection_fe_)
    else:
          f3 = str(i) + ".csv"
          intersection_fe = np.genfromtxt(f3, delimiter=',',skip_header=1,usecols=interested_col1,filling_values=0, )
          num_rows = intersection_fe.shape[0]
          intersection_fe_ = np.tile(intersection_fe[0],(num_rows,1))
          num_data = num_data + num_rows
          fe = np.append(fe,intersection_fe_)
            

  fe = fe.reshape(num_data,len(interested_col1))
  return fe 
  



# Extracting the daily number of pedestrians
dp

In [ ]:
def features_dp():

  num_loc = 94  #number of intersections
  num_data = 0  #number of all of the data points
  
  #140
  interested_col1 = [124]#extracting the interested columns
  interested_col1 = list(np.asarray(interested_col1) - 1) #python numbering is starting from 0
  #124
  interested_col2 = [108]#extracting the interested columns
  interested_col2 = list(np.asarray(interested_col2) - 1) #python numbering is starting from 0
  #44
  interested_col3 = [28]#extracting the interested columns
  interested_col3 = list(np.asarray(interested_col3) - 1) #python numbering is starting from 0
  fe = np.empty(0)
  for i in range(1,num_loc+1):
      
      
      # Order of the columns are different in some intersections
    if i == 3 or i == 4 or i == 20 or i == 27 or i == 32 or i == 53 or i == 56 or i == 59 or i == 71 or i == 93 or i == 94 :
          f1 = str(i) + ".csv"
          intersection_fe = np.genfromtxt(f1, delimiter=',',skip_header=1,usecols=interested_col2,filling_values=-1, )
          num_rows = intersection_fe.shape[0]
          num_data = num_data + num_rows
          fe = np.append(fe,intersection_fe)
    elif i == 58 or i == 2 :
          f2 = str(i) + ".csv"
          intersection_fe = np.genfromtxt(f2, delimiter=',',skip_header=1,usecols=interested_col3,filling_values=-1, )
          num_rows = intersection_fe.shape[0]
          num_data = num_data + num_rows
          fe = np.append(fe,intersection_fe)
    else:
          f3 = str(i) + ".csv"
          intersection_fe = np.genfromtxt(f3, delimiter=',',skip_header=1,usecols=interested_col1,filling_values=-1, )
          num_rows = intersection_fe.shape[0]
          num_data = num_data + num_rows
          fe = np.append(fe,intersection_fe)
            

  fe = fe.reshape(num_data,len(interested_col1))
  return fe 
  



In [ ]:
dp = features_dp()
print(dp.shape)
np.savetxt('test.csv', dp, delimiter=',', fmt='%s',  )
print(dp)

(21293, 1)
[[ 0.]
 [ 5.]
 [10.]
 ...
 [17.]
 [10.]
 [11.]]


# Extracting the dates
month/ day/ dow


In [ ]:
def features_date():

  num_loc = 94  #number of intersections
  num_data = 0  #number of all of the data points
  
  #140
  interested_col1 = [4,5,6]#extracting the interested columns
  interested_col1 = list(np.asarray(interested_col1) - 1) #python numbering is starting from 0
  #124
  interested_col2 = [4,5,6]#extracting the interested columns
  interested_col2 = list(np.asarray(interested_col2) - 1) #python numbering is starting from 0
  #44
  interested_col3 = [4,5,6]#extracting the interested columns
  interested_col3 = list(np.asarray(interested_col3) - 1) #python numbering is starting from 0
  fe = np.empty(0,dtype=int)
  for i in range(1,num_loc+1):
      
      
      # Order of the columns are different in some intersections
    if i == 3 or i == 4 or i == 20 or i == 27 or i == 32 or i == 53 or i == 56 or i == 59 or i == 71 or i == 93 or i == 94 :
          f1 = str(i) + ".csv"
          intersection_fe = np.genfromtxt(f1, delimiter=',',skip_header=1,usecols=interested_col2,filling_values=-1, )
          num_rows = intersection_fe.shape[0]
          num_data = num_data + num_rows
          fe = np.append(fe,intersection_fe)
    elif i == 58 or i == 2 :
          f2 = str(i) + ".csv"
          intersection_fe = np.genfromtxt(f2, delimiter=',',skip_header=1,usecols=interested_col3,filling_values=-1, )
          num_rows = intersection_fe.shape[0]
          num_data = num_data + num_rows
          fe = np.append(fe,intersection_fe)
    else:
          f3 = str(i) + ".csv"
          intersection_fe = np.genfromtxt(f3, delimiter=',',skip_header=1,usecols=interested_col1,filling_values=-1, )
          num_rows = intersection_fe.shape[0]
          num_data = num_data + num_rows
          fe = np.append(fe,intersection_fe)
            

  fe = fe.reshape(num_data,len(interested_col1))
  return fe 
  



In [ ]:
d = features_date()
print(d.shape)



(21293, 3)
[[ 5. 12.  6.]
 [ 5. 13.  0.]
 [ 5. 14.  1.]
 ...
 [ 9.  8.  1.]
 [ 9.  9.  2.]
 [ 9. 10.  3.]]


# Extracting the weather information
AWND/ PRCP/ SNOW/ TAVG/ TMAX/ TMIN


In [ ]:
def features_w():
  
    num_loc = 94
    w = np.empty(0)
    dates = np.empty(0,dtype=str)
    WS = pd.read_csv('TUS_amazon_csv.csv',header = 6, dtype={'date': str, 'Value': float} ,   ).fillna(0)
    WS_np_ = np.array(WS)
    WS_np = WS_np_[:,0]

    #for i in range(num_loc)
    for i in range(1, 1 + num_loc):
      W = pd.read_csv(str(i)+'.csv',header = 0, dtype={'date': str, 'Value': float} , )
      W_np = np.array(W)
      W_np_d = W_np[:,1] 
     
 
      index = np.empty(0) #index for weather information
      for j in range(len(W_np_d)):
        id = W_np_d[j]
        ind = np.where(WS_np == id)[0][0]  
        w = np.append(w,WS_np_[ind,1:7])
        dates = np.append(dates,id)
      
        
        
    w = w.reshape((-1,6))
    # where_are_nans = isnan(w)
    # w[where_are_NaNs] = 0

    return w , dates.reshape((-1,1))


In [ ]:
t , k= features_w()
print(t)
print(k)

[[3.4 2.8 0.0 18.9 25.0 13.9]
 [2.7 0.0 0.0 19.1 28.9 12.2]
 [2.2 0.0 0.0 24.0 32.8 15.6]
 ...
 [5.9 0.0 0.0 31.5 35.0 26.1]
 [3.8 0.0 0.0 27.8 32.8 20.0]
 [2.7 0.0 0.0 23.8 32.2 13.3]]
[['2019-05-12']
 ['2019-05-13']
 ['2019-05-14']
 ...
 ['2020-09-08']
 ['2020-09-09']
 ['2020-09-10']]


#Alocating STC to each data points


In [ ]:
def features_stc():

    num_loc = 94
    num_data = 0 
    w = np.empty(0)
    dates = np.empty(0,dtype=str)
    stc = np.empty(0,dtype=int)
    flags = features_fl()  #extracting the flags for validate the dates
    #_,dates = features_w()
    WS = pd.read_csv('TUS_amazon_csv.csv',header = 6, dtype={'date': str, 'Value': float} ,   ).fillna(0)
    WS_np_ = np.array(WS)
    WS_np_dates = WS_np_[:,0]
    WS_np_constants = WS_np_[:,13]
    ind = np.where(WS_np_constants == 1)[0]
    #ind2 = np.where(flags[:,1] == 0 and flags[:,2] == 0)
    


    valid_stc_days = WS_np_dates[ind]       #this is a list of valid days for STC (strings)

    for i in range(1, 1 + num_loc):

        if i == 3 or i == 4 or i == 20 or i == 27 or i == 32 or i == 53 or i == 56 or i == 59 or i == 71 or i == 93 or i == 94:
            W = pd.read_csv(str(i)+'.csv',header = 0, dtype={'date': str, 'Value': float} , )
            W_np = np.array(W)
            num_rows = W_np.shape[0]
            num_data = num_rows + num_data
            W_np_d = W_np[:,1] 
            valid_days_ind = np.where(W_np[:,113] - W_np[:,114]==0)[0] # f5 = 1 or f6 = 1 --> should be cancelled out
            W_np_valid_d = W_np_d[valid_days_ind]

            stc_ = np.empty(0) #index for weather information
            if len(W_np_valid_d) == 0:
              stc_ = 'NOT AV'
              stc = np.append(stc,np.tile(stc_,(num_rows,4)))

            else:


              for j in range(len(W_np_valid_d)):
                id = W_np_valid_d[j]
                check =  any(item in id for item in valid_stc_days) 
                #print(check)
                if check == True:
                    find = W_np_valid_d[j] == W_np_d
                    stc_where = np.where(find == 1)[0]
                    stc_ = np.append(stc_,W_np[stc_where,107])
              stc_ch = np.zeros((4,1))      
              stc_ch[0] = np.mean(stc_)   
              stc_ch[1] = np.min(stc_) 
              stc_ch[2] = np.max(stc_)  
              stc_ch[3] = np.random.choice(stc_ ,1)
              stc = np.append(stc,np.tile(stc_ch,(num_rows,1)))                              
                    
            

        elif i == 58 or i == 2 :
            W = pd.read_csv(str(i)+'.csv',header = 0, dtype={'date': str, 'Value': float} , )
            W_np = np.array(W)
            num_rows = W_np.shape[0]
            num_data = num_rows + num_data
            W_np_d = W_np[:,1] 
            valid_days_ind = np.where(W_np[:,33] - W_np[:,34]==0)[0]
            W_np_valid_d = W_np_d[valid_days_ind]

            stc_ = np.empty(0) #index for weather information
            if len(W_np_valid_d) == 0:
              stc_ = 'NOT AV'
              stc = np.append(stc,np.tile(stc_,(num_rows,4)))

            else:


              for j in range(len(W_np_valid_d)):
                id = W_np_valid_d[j]
                check =  any(item in id for item in valid_stc_days) 
                #print(check)
                if check == True:
                    find = W_np_valid_d[j] == W_np_d
                    stc_where = np.where(find == 1)[0]
                    stc_ = np.append(stc_,W_np[stc_where,27])
              stc_ch = np.zeros((4,1))      
              stc_ch[0] = np.mean(stc_)   
              stc_ch[1] = np.min(stc_) 
              stc_ch[2] = np.max(stc_)  
              stc_ch[3] = np.random.choice(stc_ ,1)
              stc = np.append(stc,np.tile(stc_ch,(num_rows,1)))                    
                    


        else:
            W = pd.read_csv(str(i)+'.csv',header = 0, dtype={'date': str, 'Value': float} , )
            W_np = np.array(W)
            num_rows = W_np.shape[0]
            num_data = num_rows + num_data
            W_np_d = W_np[:,1]  
            valid_days_ind = np.where(W_np[:,129] - W_np[:,130] == 0)[0]
            W_np_valid_d = W_np_d[valid_days_ind]

            stc_ = np.empty(0) #index for weather information
            if len(W_np_valid_d) == 0:
              stc_ = 'NOT AV'
              stc = np.append(stc,np.tile(stc_,(num_rows,4)))

            else:


              for j in range(len(W_np_valid_d)):
                id = W_np_valid_d[j]
                check =  any(item in id for item in valid_stc_days) 
                #print(check)
                if check == True:
                    find = W_np_valid_d[j] == W_np_d
                    stc_where = np.where(find == 1)[0]
                    stc_ = np.append(stc_,W_np[stc_where,123])
              stc_ch = np.zeros((4,1))      
              stc_ch[0] = np.mean(stc_)   
              stc_ch[1] = np.min(stc_) 
              stc_ch[2] = np.max(stc_)  
              stc_ch[3] = np.random.choice(stc_ ,1)
              stc = np.append(stc,np.tile(stc_ch,(num_rows,1)))



             
    
    stc = stc.reshape(-1,4)
    return stc


In [ ]:
t = features_stc()
print(t)

[['6.4' '1.0' '17.0' '7.0']
 ['6.4' '1.0' '17.0' '7.0']
 ['6.4' '1.0' '17.0' '7.0']
 ...
 ['10.6' '4.0' '17.0' '17.0']
 ['10.6' '4.0' '17.0' '17.0']
 ['10.6' '4.0' '17.0' '17.0']]


# Extracting the flags


In [ ]:
def features_fl():

  num_loc = 94  #number of intersections
  num_data = 0  #number of all of the data points
  
  #140
  interested_col1 = [130,131]#extracting the interested columns
  interested_col1 = list(np.asarray(interested_col1) - 1) #python numbering is starting from 0
  #124
  interested_col2 = [114,115]#extracting the interested columns
  interested_col2 = list(np.asarray(interested_col2) - 1) #python numbering is starting from 0
  #44
  interested_col3 = [34,35]#extracting the interested columns
  interested_col3 = list(np.asarray(interested_col3) - 1) #python numbering is starting from 0
  fe = np.empty(0)
  for i in range(1,num_loc+1):
      
      
      # Order of the columns are different in some intersections
    if i == 3 or i == 4 or i == 20 or i == 27 or i == 32 or i == 53 or i == 56 or i == 59 or i == 71 or i == 93 or i == 94 :
          f1 = str(i) + ".csv"
          intersection_fe = np.genfromtxt(f1, delimiter=',',skip_header=1,usecols=interested_col2,filling_values=-1, )
          num_rows = intersection_fe.shape[0]
          num_data = num_data + num_rows
          fe = np.append(fe,intersection_fe)
    elif i == 58 or i == 2 :
          f2 = str(i) + ".csv"
          intersection_fe = np.genfromtxt(f2, delimiter=',',skip_header=1,usecols=interested_col3,filling_values=-1, )
          num_rows = intersection_fe.shape[0]
          num_data = num_data + num_rows
          fe = np.append(fe,intersection_fe)
    else:
          f3 = str(i) + ".csv"
          intersection_fe = np.genfromtxt(f3, delimiter=',',skip_header=1,usecols=interested_col1,filling_values=-1, )
          num_rows = intersection_fe.shape[0]
          num_data = num_data + num_rows
          fe = np.append(fe,intersection_fe)
            

  fe = fe.reshape(num_data,len(interested_col1))
  return fe 
  

In [ ]:
a = features_fl()
print(a)

[[1. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


# Number of stations


In [ ]:
def features_num():
  
    num_loc = 94
    num = np.empty(0)

    #for i in range(num_loc)
    for i in range(1, 1 + num_loc):
      W = pd.read_csv(str(i)+'.csv',header = 0, dtype={'date': str, 'Value': float} , )
      num_data = np.array(W).shape[0]
      num = np.append(num,np.tile(i,(num_data,1)))
     
 
      
        
        
    num = num.reshape((-1,1))


    return num

In [ ]:
t = features_num()
print(t)


[[ 1.]
 [ 1.]
 [ 1.]
 ...
 [94.]
 [94.]
 [94.]]


# Main Code
puting all the features plus short term count value and pedestrian counts in a matrix.

In [ ]:
lu = features_lu()
d = features_date()
w , dates= features_w()
stc = features_stc()
flags = features_fl()
num = features_num()
arizona = np.concatenate((num,dates,d,w,lu,stc,flags), axis = 1)
print(arizona)
np.savetxt('arizona.csv', arizona, delimiter=',', fmt='%s',  )








[[1.0 '2019-05-12' 5.0 ... '12.0' 1.0 0.0]
 [1.0 '2019-05-13' 5.0 ... '12.0' 0.0 0.0]
 [1.0 '2019-05-14' 5.0 ... '12.0' 0.0 0.0]
 ...
 [94.0 '2020-09-08' 9.0 ... '14.0' 0.0 0.0]
 [94.0 '2020-09-09' 9.0 ... '14.0' 0.0 0.0]
 [94.0 '2020-09-10' 9.0 ... '14.0' 0.0 0.0]]
